---
name: fish-language-server
description: LSP implementation for the fish shell language
homepage: https://fish-lsp.dev
licenses:
  - MIT
languages:
  - Fish
categories:
  - LSP
source:
  # renovate:datasource=github-tags
  id: pkg:github/ndonfris/fish-lsp@v1.0.8
  build:
    run: |
      yarn install --ignore-scripts --no-progress
      yarn setup
      yarn compile
bin:
  fish-language-server: node:bin/fish-lsp
